language: python
env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: vRHkHnV3UaKJQ9l/TwQrbngF06ij9c3HhEjryhg5WCHgWLKBgwxGpX++m3pmzG32rBM7eJwtDH2m9liuXWueuh1Ae81sQzRvcOSHOJRUAWvTMXQAeTGsC6Y6OMsbiMT1OCJxuapAPPbNepVTSVu9TjbeJtabQ/yfCWZzoF4ZhnG6DNgrIPwLqVf0BUQ1zoOCHtQog9ZkcYSb5vrSnx/Ig4z4mLVvygQ6ZQElDJH+x/F508pTR8xeQH/1+BxDVctvkQDbhbFaHbNHcb2nuLLYpScFk9eJiuSHw2EZaqS5W2q9tqdGb86Fjf5fjuxT3i7+EXLI3bnVzKQsqE43nWk9p8in28jcnQDFH8oEJf4o5h3q0CEVigHn4RPGv0Lks4ESbWC7MbRS3CvpXztio+NGXKX7w66cw9E2lVhVypVKtuiUiYk9+jzXMCBUoN0IdHoWj44nt9lYqkguAU//068GZM/5iu8TJyMwssi6bYj3KLQgYSC/2etDGtLtvyMShI6uuqlVEXHWhC85IDmVZmsp/zWrQlNzabSq23gCpfXqPwlJIOSzZva+FE+H7D0oEPRwUxBNsBHa6TiMtD+TxLJM4Tsx/d1NO2xOLLyDY5j0Mqn+pIzPYDGm7vQDw/JxFVpAX2XopYUEuplsHK/FiDhrm8JgwBSzSkoiWO88++MkRks=
matrix:
  include:
    - python: 2.7
    - python: 3.6
      env:
        - BUILD_DIST=true
        - TOXENV=coveralls
    - python: 3.7
      dist: xenial
install:
  - pip install tox-travis
script:
  - tox
after_success:
  # if it's a tagged commit, upload distribution packages to pypi
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "typesupply/fontMath" ] && [ "$BUILD_SDIST" == true ]; then
        pip install --upgrade twine pip setuptools wheel
        python setup.py sdist
        pip wheel --no-deps --wheel-dir dist .
        twine upload dist/*.whl dist/*.zip
    fi
